Sprint 5/step 1
Alanhis/react-burger pull request #7
Opened 2022-12-11 05:41 UTC by Alanhis

2022-12-11 06:11 UTC, andryxxa93 requested changes
Отличная работа! Видно, что вы разобрались с вебсокетами. Хранилище типизровано верно. Основной функционал проекта соответствует брифу. Так держать!

Есть три небольших замечания - исправьте их и ваша работа будет принята.

1. Необходимо чтобы при уходе со страниц "Лента заказов" и "История заказов" вебсокет соединение закрывалось. 
2. В мидлваре сокета не хватает `send` ивента. 
3. Обратите внимание на ошибки в консоли.
<img width="618" alt="Снимок экрана 2022-12-11 в 09 06 09" src="https://user-images.githubusercontent.com/60173362/206889032-5793a9bc-f319-47e0-be92-f7cf07dbe141.png">


Рекомендация: чтобы код выглядел красиво и следовал единому стилю рекомендую использовать `eslint` и `prettier`.
https://dev.to/knowankit/setup-eslint-and-prettier-in-react-app-357b

2022-12-11 06:11 UTC, andryxxa93 commented on src/components/app/feed-element/feed-element.tsx
> +          getCookie('accessToken')?.split(' ')[1],
**Можно лучше**
Поместите функцию `.split(' ')[1]` внутрь `getCookie` раз она вам нужна при каждом вызове.

2022-12-11 11:44 UTC, Alanhis commented
Добрый день, спасибо за быстрый ответ с  вашей стороны. Закрыл некоторые недочеты, но столкнулся с некоторыми проблемами, которые я не смог понять как необходимо исправить. Поэтому хотел задать пару вопросов:
1.  Правильно ли я понимаю, что мы должны как-то поймать определенную код ошибки (в текущем случае 1001) и от него делать dispatch

2. Этот момент также не до конца понял, в качестве основы брал пример из тренажера, но не до конца понимаю когда и как он используется. Только предположил, что он может использоваться в качестве "пинг-понга", чтобы сервер из-за отсутствия какого-либо отклика не закрыл сам сокет. Не могу понять, в каком моменте он используется (через timeout раз в некоторые время или например при отправке заказа) и какие данные в него нужно передавать (получаемые мной данные или какой-то номер)

3. Большую часть ошибок закрыл, не разобрался только с 2-мя ошибками в FeedOrder и ProfileOrder, с ошибкой ниже. Тут не понятно предупреждение появляется так как где-то используется не тот тип key-а (не уникальный или наоборот) или наоборот где-то его не поставил
![image](https://user-images.githubusercontent.com/13435570/206901519-f82c7069-32f7-4b9e-904c-f4289664a6fe.png)

Извиняюсь за длинный текст, просто просидел пол дня и не могу понять каким-образом данные моменты можно полноценно закрыть. Заранее благодарю за любой ответ

2022-12-11 17:41 UTC, andryxxa93 requested changes
Исправьте одну проблему и ваша работа будет принята - 
1. Необходимо диспатчить ивент закрытия вебсокета когда размаунтиться компонент - через useEffect. Ловить ошибку для этого не нужно. Сейчас если зайти в историю
 заказов происходит ошибка - <img width="722" alt="Снимок экрана 2022-12-11 в 20 40 14" src="https://user-images.githubusercontent.com/60173362/206919596-446116c0-ba7c-4f7a-923e-e4288422bc7d.png">. 

По поводу ваших вопросов - send ивент не используется, просто для проверки, что вы усвоили материал можете его добавить в функционал мидлвара. Это не обязательно.  
С ошибкой в консоли можете не разбираться, она действительно странная, но на работу приложения не влияет.

2022-12-12 01:05 UTC, Alanhis commented
Добрый день, изменил код, теперь должен происходить закрытие вебсокета через useEffect. 

Насчет ошибки в истории заказов, при проверки она у меня не появилась, так что не до конца могу понять причины, по которой она могла вообще появиться (предполагаю, что это могло произойти из-за того, что браузер почему-то посчитал, что данные с сервера не дошли, хотя в таком случае map даже не запустился из-за проверки данных в самом return)

2022-12-12 06:08 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2022-12-12 10:10 UTC, merged